INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (1, 'Penny');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (2, 'Sheldon');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (3, 'Amy');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (4, 'Leonard');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (5, 'Bernadette');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (6, 'Raj');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (7, 'Howard');
INSERT INTO public.REST_DB_ACCESS(ID, NAME) VALUES (8, 'Priya');
